# Generated by Django 4.0.3 on 2022-03-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.developer'),
        ),
    ]
